name: Rebuild website and make it live

on:
  push:
  schedule:
    - cron: 1 9 * * 6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: date; pwd; ls -l
      - run: make setup
      - run: make render
      - run: make live
